name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "version update type"
        required: true
        type: choice
        default: "automatic"
        options:
          - "automatic"
          - "major"
          - "minor"
          - "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: pip install -r requirements.txt

      - name: Python Semantic Release Manual
        if: ${{ github.event.inputs.releaseType != 'automatic' }}
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: ${{ github.event.inputs.releaseType }}

      - name: Python Semantic Release Automatic
        if: ${{ github.event.inputs.releaseType == 'automatic' }}
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - release
    environment:
      name: pypi
      url: https://pypi.org/p/sebchw_example_package
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
